[package]
name = "search_test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
saphyr = "0.0.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
