[settings]
endpoint = "http://localhost/api/search/instant"
delay = 3000

[defaults]
limit = 50
site-language = "en"
restrict = "all"
selected-languages = ["en", "pli"]
match-partial = false

[[test-case]]
description = "Search for the metta sutta in English and Pali"
query = "metta"
selected-languages = ["pli", "en"]
hits.suttas.top_result = "/kp9/pli/ms"

[[test-case]]
description = "Has multiple dictionary results."
query = "pacch"
match-partial = true

[[test-case]]
description = "Dictionary entry with two words"
query = "pacchimo kālo"
selected-languages = ["pli"]

[[test-case]]
description = "Guide to The Linked Discourses"
query = "sn-guide-sujato"
selected-languages = ["en"]

[[test-case]]
description = "Static pages for licensing"
query = "licensing"
selected-languages = ["en"]
