[settings]
endpoint = "http://localhost/api/search/instant"
delay = 3000

[defaults]
limit = 50
site-language = "en"
restrict = "all"
selected-languages = ["en", "pli"]
match-partial = false

[[test-case]]
description = "Has multiple dictionary results."
query = "pacch"
match-partial = true

[[test-case]]
description = "Dictionary entry with two words"
query = "pacchimo kālo"
selected-languages = ["pli"]

[[test-case]]
description = "Guide to The Linked Discourses"
query = "sn guide"
selected-languages = ["en"]
expected-other = "sn-guide-sujato"
min-rank = 1

[[test-case]]
description = "Static pages for licensing"
query = "licensing"
selected-languages = ["en"]
expected.other = "licensing"

[[test-case]]
description = "Search with UID is top suttaplex result"
query = "mn1"
expected.suttaplex = "mn1"
expected.min-rank = 1

[[test-case]]
description = "Metta Sutta in Pali or English"
query = "metta"
selected-languages = ["pli", "en"]
expected.sutta = "/snp1.8/en/sujato"

[[test-case]]
description = "Metta in dictionary"
query = "metta"
selected-languages = ["pli", "en"]
expected.dictionary = "/define/metta"
expected.min-rank = 1
