[settings]
endpoint = "http://localhost/api/search/instant"
# delay = 100

[defaults]
limit = 10
site-language = "en"
restrict = "all"
match-partial = false
selected-languages = ["en", "pli"]

[[test-case]]
description = "Causes internal server error"
query = "by:sujato+\"the+Bamboo+Grove\""
match-partial = false

[[test-case]]
description = "Search is successful"
query = "dhamma"

[[test-case]]
description = "The most important sutta in Pali"
query = "dhamma"
selected-languages = ["pli"]
expected.sutta = "/an1.51-60/pli/ms"

[[test-case]]
description = "This sutta is ranked too low"
query = "snake"
selected-languages = ["en", "pli"]
expected.sutta = "/an5.77/en/sujato"
expected.min-rank = 3

[[test-case]]
description = "Metta sutta should be in the top three but isn't in results at all"
query = "metta"
expected.sutta = "/snp5.1/en/sujato"
expected.min-rank = 3

[[test-case]]
description = "Metta sutta is in the top three with partial match"
query = "metta"
match-partial = true
expected.sutta = "/snp5.1/en/sujato"
expected.min-rank = 3

[[test-case]]
description = "A pali term with diacritics"
query = "māṇavena"
expected.sutta = "/dn1/pli/ms"
expected.min-rank = 1
